package com.example.accommodationfinder

import android.content.Context
import com.example.accommodationfinder.data.Listing
import com.example.accommodationfinder.data.User
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

object SampleDataGenerator {
    
    suspend fun populateDatabase(context: Context) = withContext(Dispatchers.IO) {
        val db = AppDatabase.getDatabase(context)
        
        // Check if data already exists
        val existingUsers = db.userDao().getUserByEmail("landlord1@example.com")
        if (existingUsers != null) {
            return@withContext // Data already populated
        }

        // Create sample landlords
        val landlords = listOf(
            User(id = 101, email = "landlord1@example.com", password = "password123", name = "John Landlord", phone = "71234567"),
            User(id = 102, email = "landlord2@example.com", password = "password123", name = "Mary Properties", phone = "72345678"),
            User(id = 103, email = "landlord3@example.com", password = "password123", name = "David Homes", phone = "73456789"),
            User(id = 104, email = "landlord4@example.com", password = "password123", name = "Sarah Rentals", phone = "74567890"),
            User(id = 105, email = "landlord5@example.com", password = "password123", name = "Michael Apartments", phone = "75678901"),
        )

        landlords.forEach { db.userDao().insert(it) }

        // Create 50 sample listings
        val listings = listOf(
            Listing(title = "Cozy Studio Apartment", description = "Beautiful studio with modern furnishings. Utilities included. Secure gated compound.", price = 1500.0, location = "Gaborone", type = "Studio", amenities = "WiFi,AC,Kitchen,Laundry", availabilityDate = "2026-06-01", depositAmount = 3000.0, providerId = 101, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate, CCTV", sharingAllowed = false, transportRoutes = "Route 1, Route 5", distanceToUB = 2.5),
            Listing(title = "1-Bedroom Modern Apartment", description = "Modern 1-bedroom in Phase 2. Fully furnished, WiFi, AC. Near shops.", price = 2500.0, location = "Phase 2", type = "1-Bedroom", amenities = "WiFi,AC,Kitchen,Balcony", availabilityDate = "2026-06-15", depositAmount = 5000.0, providerId = 102, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Guard, Gate", sharingAllowed = true, transportRoutes = "Route 2, Route 8", distanceToUB = 1.8),
            Listing(title = "2-Bedroom Luxury Apartment", description = "Spacious 2-bedroom with parking. Security features include guard and CCTV.", price = 3500.0, location = "Phase 2", type = "2-Bedroom", amenities = "WiFi,AC,Kitchen,Laundry,Parking", availabilityDate = "2026-06-01", depositAmount = 7000.0, providerId = 101, imageUrl = "ic_launcher_background", utilities = "Included", security = "Guard, Gate, CCTV, Alarm", sharingAllowed = false, transportRoutes = "Route 1, Route 5", distanceToUB = 2.0),
            Listing(title = "3-Bedroom House", description = "Comfortable family home with yard and security wall. Close to UB.", price = 4500.0, location = "Tlokweng", type = "3-Bedroom", amenities = "WiFi,AC,Kitchen,Yard,Laundry", availabilityDate = "2026-07-01", depositAmount = 9000.0, providerId = 103, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate, Wall", sharingAllowed = false, transportRoutes = "Route 12, Route 3", distanceToUB = 4.5),
            Listing(title = "Studio with Kitchenette", description = "Compact studio perfect for singles. Includes kitchenette and en-suite.", price = 1800.0, location = "Gaborone", type = "Studio", amenities = "WiFi,Kitchenette,Bathroom", availabilityDate = "2026-05-15", depositAmount = 3600.0, providerId = 102, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate", sharingAllowed = true, transportRoutes = "Route 1, Route 10", distanceToUB = 3.2),
            Listing(title = "Bedsitter Near UB", description = "Perfect for students. Close to University of Botswana. Sharing allowed.", price = 1200.0, location = "UB Area", type = "Bedsitter", amenities = "Bathroom,Kitchen shared", availabilityDate = "2026-06-01", depositAmount = 2400.0, providerId = 104, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = true, transportRoutes = "Route 6, Route 7", distanceToUB = 0.5),
            Listing(title = "1-Bedroom in Block 6", description = "Affordable 1-bedroom apartment in Block 6. AC and WiFi included.", price = 2000.0, location = "Block 6", type = "1-Bedroom", amenities = "WiFi,AC,Kitchen", availabilityDate = "2026-06-20", depositAmount = 4000.0, providerId = 105, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate, Guard", sharingAllowed = false, transportRoutes = "Route 4, Route 9", distanceToUB = 3.8),
            Listing(title = "2-Bedroom in Mogoditshane", description = "Spacious 2-bedroom house in quiet Mogoditshane. Family-friendly.", price = 3000.0, location = "Mogoditshane", type = "2-Bedroom", amenities = "Kitchen,Bathroom,Yard", availabilityDate = "2026-07-15", depositAmount = 6000.0, providerId = 103, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = false, transportRoutes = "Route 11, Route 12", distanceToUB = 6.5),
            Listing(title = "Studio Apartment in Phase 2", description = "Modern studio with full amenities. Excellent location near shops.", price = 2200.0, location = "Phase 2", type = "Studio", amenities = "WiFi,AC,Kitchen,Shower", availabilityDate = "2026-06-05", depositAmount = 4400.0, providerId = 101, imageUrl = "ic_launcher_background", utilities = "Included", security = "CCTV, Gate", sharingAllowed = false, transportRoutes = "Route 2, Route 5", distanceToUB = 1.5),
            Listing(title = "1-Bedroom Student Flat", description = "Budget-friendly 1-bedroom perfect for students. Sharing area available.", price = 1600.0, location = "UB Area", type = "1-Bedroom", amenities = "WiFi,Kitchen,Bathroom", availabilityDate = "2026-06-01", depositAmount = 3200.0, providerId = 102, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = true, transportRoutes = "Route 6, Route 8", distanceToUB = 0.8),
            Listing(title = "2-Bedroom Premium Apartment", description = "Premium 2-bedroom with modern kitchen and high-speed WiFi.", price = 4000.0, location = "Gaborone", type = "2-Bedroom", amenities = "WiFi,AC,Kitchen,Laundry,Parking", availabilityDate = "2026-06-10", depositAmount = 8000.0, providerId = 104, imageUrl = "ic_launcher_background", utilities = "Included", security = "Guard, CCTV, Gate, Alarm", sharingAllowed = false, transportRoutes = "Route 1, Route 5", distanceToUB = 2.8),
            Listing(title = "Compact Bedsitter", description = "Small but comfortable bedsitter. Sharing kitchen and bathroom.", price = 900.0, location = "Block 6", type = "Bedsitter", amenities = "Bathroom,Kitchen shared", availabilityDate = "2026-05-20", depositAmount = 1800.0, providerId = 105, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = true, transportRoutes = "Route 4, Route 10", distanceToUB = 4.0),
            Listing(title = "1-Bedroom with Parking", description = "Modern 1-bedroom with dedicated parking space. Great for professionals.", price = 2800.0, location = "Phase 2", type = "1-Bedroom", amenities = "WiFi,AC,Kitchen,Parking,Balcony", availabilityDate = "2026-06-25", depositAmount = 5600.0, providerId = 101, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate, Guard, CCTV", sharingAllowed = false, transportRoutes = "Route 2, Route 8", distanceToUB = 1.2),
            Listing(title = "3-Bedroom Family Home", description = "Spacious 3-bedroom home with all amenities. Family-oriented community.", price = 5000.0, location = "Tlokweng", type = "3-Bedroom", amenities = "WiFi,AC,Kitchen,Yard,Laundry,Parking", availabilityDate = "2026-07-01", depositAmount = 10000.0, providerId = 102, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate, Wall, CCTV", sharingAllowed = false, transportRoutes = "Route 12, Route 3", distanceToUB = 5.0),
            Listing(title = "Studio Near Shops", description = "Convenient studio location. Close to shopping centers and restaurants.", price = 1900.0, location = "Gaborone", type = "Studio", amenities = "WiFi,AC,Kitchen,Bathroom", availabilityDate = "2026-06-08", depositAmount = 3800.0, providerId = 103, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate", sharingAllowed = true, transportRoutes = "Route 1, Route 10", distanceToUB = 3.5),
            Listing(title = "1-Bedroom Affordable", description = "Good value 1-bedroom apartment with basic amenities.", price = 2100.0, location = "Mogoditshane", type = "1-Bedroom", amenities = "Kitchen,Bathroom,Living area", availabilityDate = "2026-06-30", depositAmount = 4200.0, providerId = 104, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = false, transportRoutes = "Route 11, Route 12", distanceToUB = 6.0),
            Listing(title = "2-Bedroom Standard", description = "Standard 2-bedroom apartment with all basic amenities included.", price = 3200.0, location = "Phase 2", type = "2-Bedroom", amenities = "WiFi,AC,Kitchen,Bathroom", availabilityDate = "2026-06-12", depositAmount = 6400.0, providerId = 105, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate, Guard", sharingAllowed = false, transportRoutes = "Route 2, Route 8", distanceToUB = 1.8),
            Listing(title = "Budget Studio", description = "Very affordable studio for budget-conscious renters.", price = 1300.0, location = "UB Area", type = "Studio", amenities = "Bathroom,Basic kitchen", availabilityDate = "2026-05-25", depositAmount = 2600.0, providerId = 101, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = true, transportRoutes = "Route 6, Route 7", distanceToUB = 1.2),
            Listing(title = "1-Bedroom Premium", description = "Upscale 1-bedroom with premium finishes and quality furniture.", price = 3100.0, location = "Gaborone", type = "1-Bedroom", amenities = "WiFi,AC,Kitchen,Balcony,Laundry", availabilityDate = "2026-06-18", depositAmount = 6200.0, providerId = 102, imageUrl = "ic_launcher_background", utilities = "Included", security = "Guard, CCTV, Alarm", sharingAllowed = false, transportRoutes = "Route 1, Route 5", distanceToUB = 2.5),
            Listing(title = "2-Bedroom Budget", description = "Budget-friendly 2-bedroom for families. Basic furnishings provided.", price = 2600.0, location = "Block 6", type = "2-Bedroom", amenities = "Kitchen,Bathroom", availabilityDate = "2026-07-05", depositAmount = 5200.0, providerId = 103, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = false, transportRoutes = "Route 4, Route 9", distanceToUB = 4.2),
            Listing(title = "Bedsitter Plus", description = "Bedsitter with extra storage space and upgraded amenities.", price = 1400.0, location = "Phase 2", type = "Bedsitter", amenities = "Bathroom,Kitchen shared,Storage", availabilityDate = "2026-06-22", depositAmount = 2800.0, providerId = 104, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate, Guard", sharingAllowed = true, transportRoutes = "Route 2, Route 8", distanceToUB = 1.5),
            Listing(title = "Studio with Balcony", description = "Nice studio with private balcony overlooking the city.", price = 2400.0, location = "Gaborone", type = "Studio", amenities = "WiFi,AC,Kitchen,Balcony,Bathroom", availabilityDate = "2026-06-03", depositAmount = 4800.0, providerId = 105, imageUrl = "ic_launcher_background", utilities = "Included", security = "CCTV, Gate", sharingAllowed = false, transportRoutes = "Route 1, Route 10", distanceToUB = 3.0),
            Listing(title = "1-Bedroom Cozy", description = "Warm and cozy 1-bedroom apartment. Perfect for couples.", price = 2300.0, location = "Mogoditshane", type = "1-Bedroom", amenities = "WiFi,AC,Kitchen,Bathroom", availabilityDate = "2026-06-28", depositAmount = 4600.0, providerId = 101, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate", sharingAllowed = false, transportRoutes = "Route 11, Route 12", distanceToUB = 6.2),
            Listing(title = "2-Bedroom Classic", description = "Classic 2-bedroom design with traditional charm and comfort.", price = 3400.0, location = "UB Area", type = "2-Bedroom", amenities = "Kitchen,Bathroom,Living area,Yard", availabilityDate = "2026-07-10", depositAmount = 6800.0, providerId = 102, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = false, transportRoutes = "Route 6, Route 8", distanceToUB = 0.7),
            Listing(title = "Studio Executive", description = "Executive studio with premium amenities and services.", price = 2700.0, location = "Phase 2", type = "Studio", amenities = "WiFi,AC,Kitchen,Laundry,Gym access", availabilityDate = "2026-06-09", depositAmount = 5400.0, providerId = 103, imageUrl = "ic_launcher_background", utilities = "Included", security = "Guard, CCTV, Gate", sharingAllowed = false, transportRoutes = "Route 2, Route 5", distanceToUB = 1.3),
            Listing(title = "1-Bedroom Value", description = "Great value 1-bedroom with reasonable pricing.", price = 1900.0, location = "Block 6", type = "1-Bedroom", amenities = "WiFi,Kitchen,Bathroom", availabilityDate = "2026-06-20", depositAmount = 3800.0, providerId = 104, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = false, transportRoutes = "Route 4, Route 10", distanceToUB = 3.9),
            Listing(title = "2-Bedroom Comfort", description = "Comfortable 2-bedroom with excellent amenities and services.", price = 3700.0, location = "Gaborone", type = "2-Bedroom", amenities = "WiFi,AC,Kitchen,Balcony,Laundry,Parking", availabilityDate = "2026-06-14", depositAmount = 7400.0, providerId = 105, imageUrl = "ic_launcher_background", utilities = "Included", security = "Guard, CCTV, Alarm", sharingAllowed = false, transportRoutes = "Route 1, Route 5", distanceToUB = 2.3),
            Listing(title = "Bedsitter Economy", description = "Economy bedsitter for the budget-conscious student.", price = 1000.0, location = "UB Area", type = "Bedsitter", amenities = "Bathroom,Kitchen shared", availabilityDate = "2026-05-30", depositAmount = 2000.0, providerId = 101, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = true, transportRoutes = "Route 6, Route 7", distanceToUB = 0.4),
            Listing(title = "Studio Deluxe", description = "Deluxe studio with all modern conveniences and luxuries.", price = 2900.0, location = "Phase 2", type = "Studio", amenities = "WiFi,AC,Kitchen,Laundry,Bathroom,Parking", availabilityDate = "2026-06-26", depositAmount = 5800.0, providerId = 102, imageUrl = "ic_launcher_background", utilities = "Included", security = "Guard, CCTV, Gate", sharingAllowed = false, transportRoutes = "Route 2, Route 8", distanceToUB = 1.1),
            Listing(title = "1-Bedroom Trendy", description = "Trendy 1-bedroom with contemporary design and furnishings.", price = 2600.0, location = "Mogoditshane", type = "1-Bedroom", amenities = "WiFi,AC,Kitchen,Balcony,Laundry", availabilityDate = "2026-07-08", depositAmount = 5200.0, providerId = 103, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate", sharingAllowed = false, transportRoutes = "Route 11, Route 12", distanceToUB = 6.3),
            Listing(title = "2-Bedroom Extra", description = "Extra spacious 2-bedroom with additional living areas.", price = 4100.0, location = "Gaborone", type = "2-Bedroom", amenities = "WiFi,AC,Kitchen,Laundry,Parking,Balcony", availabilityDate = "2026-06-19", depositAmount = 8200.0, providerId = 104, imageUrl = "ic_launcher_background", utilities = "Included", security = "Guard, CCTV, Alarm", sharingAllowed = false, transportRoutes = "Route 1, Route 5", distanceToUB = 2.6),
            Listing(title = "Studio Compact", description = "Compact studio with efficient space utilization.", price = 1700.0, location = "Block 6", type = "Studio", amenities = "WiFi,Kitchen,Bathroom", availabilityDate = "2026-06-24", depositAmount = 3400.0, providerId = 105, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = true, transportRoutes = "Route 4, Route 9", distanceToUB = 4.1),
            Listing(title = "1-Bedroom Spacious", description = "Spacious 1-bedroom with lots of natural light.", price = 2450.0, location = "UB Area", type = "1-Bedroom", amenities = "WiFi,AC,Kitchen,Bathroom,Balcony", availabilityDate = "2026-06-11", depositAmount = 4900.0, providerId = 101, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate, Guard", sharingAllowed = false, transportRoutes = "Route 6, Route 8", distanceToUB = 0.9),
            Listing(title = "2-Bedroom Elite", description = "Elite 2-bedroom with exclusive amenities and services.", price = 4300.0, location = "Phase 2", type = "2-Bedroom", amenities = "WiFi,AC,Kitchen,Laundry,Parking,Gym,Pool", availabilityDate = "2026-06-27", depositAmount = 8600.0, providerId = 102, imageUrl = "ic_launcher_background", utilities = "Included", security = "Guard, CCTV, Gate, Alarm", sharingAllowed = false, transportRoutes = "Route 2, Route 5", distanceToUB = 1.0),
            Listing(title = "Bedsitter Standard", description = "Standard bedsitter with decent facilities and amenities.", price = 1100.0, location = "Mogoditshane", type = "Bedsitter", amenities = "Bathroom,Kitchen shared,Storage", availabilityDate = "2026-06-16", depositAmount = 2200.0, providerId = 103, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = true, transportRoutes = "Route 11, Route 12", distanceToUB = 5.9),
            Listing(title = "Studio Bright", description = "Bright and airy studio with lots of windows.", price = 2050.0, location = "Gaborone", type = "Studio", amenities = "WiFi,AC,Kitchen,Bathroom", availabilityDate = "2026-06-21", depositAmount = 4100.0, providerId = 104, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate", sharingAllowed = false, transportRoutes = "Route 1, Route 10", distanceToUB = 3.1),
            Listing(title = "1-Bedroom Modern", description = "Modern 1-bedroom with updated appliances.", price = 2550.0, location = "Block 6", type = "1-Bedroom", amenities = "WiFi,AC,Kitchen,Bathroom,Balcony", availabilityDate = "2026-06-30", depositAmount = 5100.0, providerId = 105, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate, Guard", sharingAllowed = false, transportRoutes = "Route 4, Route 9", distanceToUB = 4.3),
            Listing(title = "2-Bedroom Ready", description = "Ready to move in 2-bedroom apartment.", price = 3300.0, location = "UB Area", type = "2-Bedroom", amenities = "WiFi,AC,Kitchen,Laundry,Bathroom", availabilityDate = "2026-07-02", depositAmount = 6600.0, providerId = 101, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate", sharingAllowed = false, transportRoutes = "Route 6, Route 8", distanceToUB = 0.6),
            Listing(title = "Studio Sweet", description = "Sweet little studio perfect for one person.", price = 1550.0, location = "Phase 2", type = "Studio", amenities = "WiFi,Kitchen,Bathroom", availabilityDate = "2026-06-07", depositAmount = 3100.0, providerId = 102, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = true, transportRoutes = "Route 2, Route 8", distanceToUB = 1.4),
            Listing(title = "1-Bedroom Happy", description = "Happy place 1-bedroom with warm atmosphere.", price = 2350.0, location = "Mogoditshane", type = "1-Bedroom", amenities = "WiFi,AC,Kitchen,Bathroom", availabilityDate = "2026-07-04", depositAmount = 4700.0, providerId = 103, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate", sharingAllowed = false, transportRoutes = "Route 11, Route 12", distanceToUB = 6.1),
            Listing(title = "2-Bedroom Enjoy", description = "Enjoy life in this wonderful 2-bedroom home.", price = 3850.0, location = "Gaborone", type = "2-Bedroom", amenities = "WiFi,AC,Kitchen,Laundry,Parking,Balcony", availabilityDate = "2026-06-23", depositAmount = 7700.0, providerId = 104, imageUrl = "ic_launcher_background", utilities = "Included", security = "Guard, CCTV, Gate", sharingAllowed = false, transportRoutes = "Route 1, Route 5", distanceToUB = 2.4),
            Listing(title = "Bedsitter Lite", description = "Lite version bedsitter for minimalist living.", price = 950.0, location = "Block 6", type = "Bedsitter", amenities = "Bathroom,Kitchen shared", availabilityDate = "2026-06-17", depositAmount = 1900.0, providerId = 105, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = true, transportRoutes = "Route 4, Route 10", distanceToUB = 4.0),
            Listing(title = "Studio Zen", description = "Zen studio for peaceful living and meditation.", price = 2150.0, location = "UB Area", type = "Studio", amenities = "WiFi,AC,Kitchen,Bathroom,Balcony", availabilityDate = "2026-06-13", depositAmount = 4300.0, providerId = 101, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate", sharingAllowed = false, transportRoutes = "Route 6, Route 7", distanceToUB = 0.5),
            Listing(title = "1-Bedroom Perfect", description = "Perfect 1-bedroom for your needs and lifestyle.", price = 2700.0, location = "Phase 2", type = "1-Bedroom", amenities = "WiFi,AC,Kitchen,Laundry,Bathroom,Balcony", availabilityDate = "2026-07-06", depositAmount = 5400.0, providerId = 102, imageUrl = "ic_launcher_background", utilities = "Included", security = "Guard, Gate, CCTV", sharingAllowed = false, transportRoutes = "Route 2, Route 5", distanceToUB = 1.2),
            Listing(title = "2-Bedroom Dream", description = "Dream 2-bedroom home with all amenities.", price = 4200.0, location = "Mogoditshane", type = "2-Bedroom", amenities = "WiFi,AC,Kitchen,Laundry,Parking,Yard", availabilityDate = "2026-07-12", depositAmount = 8400.0, providerId = 103, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate, Wall, CCTV", sharingAllowed = false, transportRoutes = "Route 11, Route 12", distanceToUB = 6.4),
            Listing(title = "Studio Home", description = "Home-like studio with comfortable setup.", price = 1850.0, location = "Gaborone", type = "Studio", amenities = "WiFi,AC,Kitchen,Bathroom", availabilityDate = "2026-06-29", depositAmount = 3700.0, providerId = 104, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = true, transportRoutes = "Route 1, Route 10", distanceToUB = 3.3),
            Listing(title = "1-Bedroom Nice", description = "Nice 1-bedroom with pleasant surroundings.", price = 2200.0, location = "Block 6", type = "1-Bedroom", amenities = "WiFi,Kitchen,Bathroom", availabilityDate = "2026-06-19", depositAmount = 4400.0, providerId = 105, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate", sharingAllowed = false, transportRoutes = "Route 4, Route 9", distanceToUB = 3.7),
            Listing(title = "2-Bedroom Best", description = "Best 2-bedroom option for comfortable living.", price = 3600.0, location = "UB Area", type = "2-Bedroom", amenities = "WiFi,AC,Kitchen,Bathroom,Balcony", availabilityDate = "2026-07-09", depositAmount = 7200.0, providerId = 101, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate", sharingAllowed = false, transportRoutes = "Route 6, Route 8", distanceToUB = 0.8),
            Listing(title = "Bedsitter Plus+", description = "Bedsitter Plus Plus with extra features.", price = 1350.0, location = "Phase 2", type = "Bedsitter", amenities = "Bathroom,Kitchen shared,Storage,WiFi", availabilityDate = "2026-06-02", depositAmount = 2700.0, providerId = 102, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate, Guard", sharingAllowed = true, transportRoutes = "Route 2, Route 8", distanceToUB = 1.6),
            Listing(title = "Studio Relax", description = "Relax in this comfortable studio apartment.", price = 2300.0, location = "Mogoditshane", type = "Studio", amenities = "WiFi,AC,Kitchen,Bathroom", availabilityDate = "2026-06-25", depositAmount = 4600.0, providerId = 103, imageUrl = "ic_launcher_background", utilities = "Included", security = "Gate", sharingAllowed = false, transportRoutes = "Route 11, Route 12", distanceToUB = 6.0),
            Listing(title = "1-Bedroom Plus", description = "1-Bedroom Plus with extra storage and space.", price = 2750.0, location = "Gaborone", type = "1-Bedroom", amenities = "WiFi,AC,Kitchen,Laundry,Bathroom,Balcony", availabilityDate = "2026-07-01", depositAmount = 5500.0, providerId = 104, imageUrl = "ic_launcher_background", utilities = "Included", security = "Guard, CCTV, Gate", sharingAllowed = false, transportRoutes = "Route 1, Route 5", distanceToUB = 2.2),
            Listing(title = "2-Bedroom Living", description = "2-Bedroom Perfect for comfortable living.", price = 3550.0, location = "Block 6", type = "2-Bedroom", amenities = "WiFi,AC,Kitchen,Bathroom", availabilityDate = "2026-07-03", depositAmount = 7100.0, providerId = 105, imageUrl = "ic_launcher_background", utilities = "Separate", security = "Gate, Guard", sharingAllowed = false, transportRoutes = "Route 4, Route 9", distanceToUB = 4.2),
        )

        listings.forEach { db.listingDao().insert(it) }
    }
}
